name: 'CD Tests'
on:
  push:
    branches:
      - 'master'
    paths:
      - '**'
env:
  TEST_ENV_VAR: 'test_env_var_value'

jobs:
  test:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.9
          uses: actions/setup-python@v2
          with:
            python-version: 3.9

        - name: Install dependencies
          working-directory: '.'
          run: pip install pytest pandas scikit-learn numpy

        - name: Run Unit tests
          working-directory: '.'
          run: pytest tests/unit/